/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.awt.image.BufferedImage;

public class App {


    public static void main(String[] args){
        BitMap bitMap = new BitMap(args[0]);
        while(args.length > 0){
            if(args[2].equals("invert")){
                bitMap.invert();
            }
        }
    }




}
